print "Hello World!"
print "Hello World!"
print "Can ya'll see me, all of you?"
print "Can't you? Then it must be the light problem."
#print "To be honest, I don't trust you, for you had fooled me once."
print "But please don't trick me again, for I have a really weak heart."
#print "Just please..."